// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dwHl-khM4BVM_znEpp3L5oyI4hLxjkA',
    appId: '1:247040593587:web:f511cf362b6cd091826ac6',
    messagingSenderId: '247040593587',
    projectId: 'location-156a2',
    authDomain: 'location-156a2.firebaseapp.com',
    storageBucket: 'location-156a2.firebasestorage.app',
    measurementId: 'G-KRBJY9PF7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezAitF3Gfy-2Nbp3SQxwMk344JEHNbG8',
    appId: '1:247040593587:android:90314c158d939853826ac6',
    messagingSenderId: '247040593587',
    projectId: 'location-156a2',
    storageBucket: 'location-156a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34JvGF8o3u1gEtI8RS_ckfydAfInIMNw',
    appId: '1:247040593587:ios:a59028fbe1e8c61e826ac6',
    messagingSenderId: '247040593587',
    projectId: 'location-156a2',
    storageBucket: 'location-156a2.firebasestorage.app',
    iosBundleId: 'uz.flutterblog.anziratApp',
  );

}